base:
    font: ./fonts/SourceHanSansCN-Light.otf
    bold_font: ./fonts/SourceHanSansCN-Bold.otf
    input_dir: ./input
    output_dir: ./output
    quality: 100
    
logo:
    enable: true
    makes:
        nikon:
            id: NIKON
            path: ./logos/nikon.png
        canon:
            id: Canon
            path: ./logos/canon.png
        sony:
            id: SONY
            path: ./logos/sony.png
        pentax:
            id: PENTAX
            path: ./logos/pentax.png
        panasonic:
            id: Panasonic
            path: ./logos/panasonic.png
        olympus:
            id: Olympus
            path: ./logos/olympus_blue_gold.png
        fujifilm:
            id: FUJIFILM
            path: ./logos/fujifilm.png