base:
    font: ./fonts/SourceHanSansCN-Light.otf
    bold_font: ./fonts/SourceHanSansCN-Bold.otf
    input_dir: ./input
    output_dir: ./output
    quality: 100
    
logo:
    enable: true
    makes:
        nikon:
            id: NIKON
            path: ./logos/nikon.png
        canon:
            id: Canon
            path: ./logos/canon.png
        sony:
            id: SONY
            path: ./logos/sony.png
        pentax:
            id: PENTAX
            path: ./logos/pentax.png
        panasonic:
            id: Panasonic
            path: ./logos/panasonic.png
        olympus:
            id: Olympus
            path: ./logos/olympus_blue_gold.png
        fujifilm:
            id: FUJIFILM
            path: ./logos/fujifilm.png
        leica:
            id: leica
            path: ./logos/leica_logo.png
        rioch:
            id: RIOCH
            path: ./logos/ricoh.png
        hasselblad:
            id: HASSELBLAD
            path: ./logos/hasselblad.png

left:
    enable: true
    # 可选项有厂商 (Company)，机型 (Model) 和镜头 (Lens)
    first: Company
    second: Model

right:
    enable: true
    # 可选项有拍摄参数 (Param) 和拍摄日期 (Date)
    first: Param
    second: Date
